// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts(id, created_at, updated_at, title, url, description, published_at, feed_id)
VALUES($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(url) DO NOTHING
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const getPostForUser = `-- name: GetPostForUser :many
SELECT p.id, p.created_at, p.updated_at, p.title, p.url, p.description, p.published_at, p.feed_id, f.name as feed_name
FROM posts p
JOIN feed_follows ff ON ff.feed_id = p.feed_id
JOIN feeds f ON p.feed_id = f.id
WHERE ff.user_id = $1
ORDER BY p.published_at DESC
`

type GetPostForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      uuid.UUID
	FeedName    string
}

func (q *Queries) GetPostForUser(ctx context.Context, userID uuid.UUID) ([]GetPostForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostForUserRow
	for rows.Next() {
		var i GetPostForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNumberForUser = `-- name: GetUnreadNumberForUser :one
SELECT COUNT(*) FROM posts p
JOIN feed_follows ff ON ff.feed_id = p.feed_id
WHERE ff.user_id = $1 AND p.read = False
`

func (q *Queries) GetUnreadNumberForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNumberForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markPostAsRead = `-- name: MarkPostAsRead :exec
UPDATE posts SET read = TRUE, UPDATED_AT = NOW() WHERE id = $1
`

func (q *Queries) MarkPostAsRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPostAsRead, id)
	return err
}

const markPostAsUnread = `-- name: MarkPostAsUnread :exec
UPDATE posts SET read = FALSE, UPDATED_AT = NOW() WHERE id = $1
`

func (q *Queries) MarkPostAsUnread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPostAsUnread, id)
	return err
}
