-- +goose Up
ALTER TABLE posts ALTER COLUMN title TYPE TEXT;
ALTER TABLE posts ALTER COLUMN url TYPE TEXT;

-- +goose Down
ALTER TABLE posts ALTER COLUMN title TYPE VARCHAR(255);
ALTER TABLE posts ALTER COLUMN url TYPE VARCHAR(255);